export const data = [
  {
    id: 1,
    english: "ginger",
    transcription: "[ˈʤɪnʤə]",
    russian: "имбирь",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "2",
    english: "waterfall",
    transcription: "[ˈwɔ:təfɔ:l]",
    russian: "водопад",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "3",
    english: "story",
    transcription: "[ˈstôrē]",
    russian: "история",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "4",
    english: "first",
    transcription: "[fərst]",
    russian: "первый",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "5",
    english: "sucсess",
    transcription: "[sucsess]",
    russian: "успех",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "6",
    english: "sunset",
    transcription: "[ˈsʌnset]",
    russian: "закат",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "7",
    english: "wind",
    transcription: "[wind]",
    russian: "ветер",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "8",
    english: "field",
    transcription: "[fi:ld]",
    russian: "поле",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "9",
    english: "cat",
    transcription: "[cat]",
    russian: "кот",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "10",
    english: "ground",
    transcription: "[gra:und]",
    russian: "земля",
    tags: "",
    tags_json: "[]",
  },
  {
    id: "11",
    english: "book",
    transcription: "[buk]",
    russian: "книжка",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "12",
    english: "thunderstorm",
    transcription: " [ˈθʌndəstɔ:m]",
    russian: "гроза",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "13",
    english: "sky",
    transcription: "[skaɪ]",
    russian: "небо",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "14",
    english: "story",
    transcription: "[ˈstôrē]",
    russian: "история",
    tags: "",
    tags_json: '[""]',
  },
];
